
const DOMAIN = '@@POKEMON';

export const POKEMON_FETCH = `${DOMAIN}/POKEMON_FETCH`;
export const POKEMON_FETCH_SUCCESS = `${DOMAIN}/POKEMON_FETCH_SUCCESS`;
export const POKEMON_FETCH_FAIL = `${DOMAIN}/POKEMON_FETCH_FAIL`;
