
const DOMAIN = '@@SEARCH';

export const SEARCH_POKEMONS = `${DOMAIN}/SEARCH_POKEMONS`;
export const SEARCH_POKEMONS_SUCCESS = `${DOMAIN}/SEARCH_POKEMONS_SUCCESS`;
export const SEARCH_POKEMONS_FAIL = `${DOMAIN}/SEARCH_POKEMONS_FAIL`;

